// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CatatKas.Models;

[Index("user_id", "year", "month", Name = "idx_budgets_lookup")]
[Index("user_id", "category_id", "month", "year", Name = "unique_user_category_month_year", IsUnique = true)]
public partial class budgets
{
    [Key]
    public int id { get; set; }

    public long user_id { get; set; }

    public int category_id { get; set; }

    [Column(TypeName = "decimal(15, 2)")]
    public decimal amount { get; set; }

    public byte month { get; set; }

    public int year { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? created_at { get; set; }

    [ForeignKey("category_id")]
    [InverseProperty("budgets")]
    public virtual categories category { get; set; }

    [ForeignKey("user_id")]
    [InverseProperty("budgets")]
    public virtual users user { get; set; }
}