// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace CatatKas.Models;

public partial class CatatKasContext : DbContext
{
    public CatatKasContext(DbContextOptions<CatatKasContext> options)
        : base(options)
    {
    }

    public virtual DbSet<budgets> budgets { get; set; }

    public virtual DbSet<categories> categories { get; set; }

    public virtual DbSet<transactions> transactions { get; set; }

    public virtual DbSet<users> users { get; set; }

    public virtual DbSet<wallets> wallets { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<budgets>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__budgets__3213E83F5D73536C");

            entity.Property(e => e.created_at).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.category).WithMany(p => p.budgets)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__budgets__categor__398D8EEE");

            entity.HasOne(d => d.user).WithMany(p => p.budgets).HasConstraintName("FK__budgets__user_id__38996AB5");
        });

        modelBuilder.Entity<categories>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__categori__3213E83F1297819E");

            entity.Property(e => e.created_at).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.user).WithMany(p => p.categories)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK__categorie__user___286302EC");
        });

        modelBuilder.Entity<transactions>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__transact__3213E83FFE716C42");

            entity.Property(e => e.created_at).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.transaction_date).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.category).WithMany(p => p.transactions)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__transacti__categ__32E0915F");

            entity.HasOne(d => d.user).WithMany(p => p.transactions).HasConstraintName("FK__transacti__user___30F848ED");

            entity.HasOne(d => d.wallet).WithMany(p => p.transactions)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__transacti__walle__31EC6D26");
        });

        modelBuilder.Entity<users>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__users__3213E83FC5206D61");

            entity.Property(e => e.created_at).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<wallets>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__wallets__3213E83F1D436803");

            entity.Property(e => e.balance).HasDefaultValue(0.00m);
            entity.Property(e => e.created_at).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.user).WithMany(p => p.wallets).HasConstraintName("FK__wallets__user_id__2C3393D0");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}