// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CatatKas.Models;

public partial class categories
{
    [Key]
    public int id { get; set; }

    public long? user_id { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string name { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string icon { get; set; }

    [StringLength(7)]
    [Unicode(false)]
    public string color { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? created_at { get; set; }

    [InverseProperty("category")]
    public virtual ICollection<budgets> budgets { get; set; } = new List<budgets>();

    [InverseProperty("category")]
    public virtual ICollection<transactions> transactions { get; set; } = new List<transactions>();

    [ForeignKey("user_id")]
    [InverseProperty("categories")]
    public virtual users user { get; set; }
}