// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CatatKas.Models;

[Index("user_id", "transaction_date", Name = "idx_transactions_user_date")]
public partial class transactions
{
    [Key]
    public long id { get; set; }

    public long user_id { get; set; }

    public int wallet_id { get; set; }

    public int category_id { get; set; }

    [Column(TypeName = "decimal(15, 2)")]
    public decimal amount { get; set; }

    public string description { get; set; }

    public DateOnly transaction_date { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? created_at { get; set; }

    [ForeignKey("category_id")]
    [InverseProperty("transactions")]
    public virtual categories category { get; set; }

    [ForeignKey("user_id")]
    [InverseProperty("transactions")]
    public virtual users user { get; set; }

    [ForeignKey("wallet_id")]
    [InverseProperty("transactions")]
    public virtual wallets wallet { get; set; }
}