// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CatatKas.Models;

[Index("email", Name = "UQ__users__AB6E616433AA0603", IsUnique = true)]
public partial class users
{
    [Key]
    public long id { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string name { get; set; }

    [Required]
    [StringLength(150)]
    [Unicode(false)]
    public string email { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string password_hash { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? created_at { get; set; }

    [InverseProperty("user")]
    public virtual ICollection<budgets> budgets { get; set; } = new List<budgets>();

    [InverseProperty("user")]
    public virtual ICollection<categories> categories { get; set; } = new List<categories>();

    [InverseProperty("user")]
    public virtual ICollection<transactions> transactions { get; set; } = new List<transactions>();

    [InverseProperty("user")]
    public virtual ICollection<wallets> wallets { get; set; } = new List<wallets>();
}